apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: kubedb-manifest-addon
spec:
  backupTasks:
    - name: manifest-backup
      function: kubedb-manifest-backup
      singleton: true
      driver: Restic 
  restoreTasks:
    - name: manifest-restore
      function: kubedb-manifest-restore
      singleton: true
      driver: Restic