apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  name: kubedb-manifest-addon
spec:
  backupTasks:
    - name: manifest-backup
      function: kubedb-manifest-backup
      driver: Restic 
      executor: Job 
  restoreTasks:
    - name: manifest-restore
      function: kubedb-manifest-restore
      driver: Restic
      executor: Job