apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: kubedb-manifest-backup
spec:
  image: hmsayem/kubedb-manifest:fix-snapshot-component_linux_amd64
  args:
  - backup
  - --scratchDir=${scratchDir:=/tmp}
  - --namespace=${namespace:=default}
  - --backupSession=${backupSession:=}
  - --targetKind=${targetKind:=}
  - --targetNamespace=${targetNamespace:=default}
  - --targetName=${targetName:=}
---
apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  name: kubedb-manifest-restore
spec:
  image: hmsayem/kubedb-manifest:fix-snapshot-component_linux_amd64
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoreSession=${restoreSession:=}
  - --targetKind=${targetKind:=}
  - --restoreNamespace=${restoreNamespace:=default}
  - --mongoYaml=${mongoYaml:=true}
  - --mongoName=${mongoDBName:=}
  - --pgYaml=${pgYaml:=true}
  - --pgName=${pgName:=}
  - --authSecretYaml=${authSecretYaml:=true}
  - --authSecretName=${authSecretName:=}
  - --configSecretYaml=${configSecretYaml:=true}
  - --configSecretName=${configSecretName:=}
