apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: sample-restoresession
  namespace: demo
spec:
  manifestOptions:
    restoreNamespace: demo2
    mongoDB:
      db: true
      dbName: new-mongodb
      authSecret: true
      configSecret: true
  dataSource:
    snapshot: latest
    repository: s3-repo
    encryptionSecret:
      name: encry-secret 
      namespace: demo
  addon:
    name: kubedb-manifest-addon
    tasks:
      - name: manifest-restore