apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: sample-backup
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: StatefulSet
    name: web
    namespace: demo
  backends:
  - name: s3-storage
    storageRef:
      apiGroup: storage.kubestash.com
      namespace: demo
      kind: BackupStorage
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: workload-backup
    sessionHistoryLimit: 3
    scheduler: # CronJob specification
      schedule: "*/2 * * * *"
      jobTemplate: # Comes from batch/v1 JobTemplateSpec
        backoffLimit: 1
    repositories: # volume & volumeMount strategy.
    - name: demo-storage-0
      backend: s3-storage
      directory: /dep/sts
      encryptionSecret:
        name: encry-secret # some addon may not support encryption
        namespace: demo
    addon:
      name: workload-addon
      tasks:
      - name: workload-backup
        targetVolumes:
          volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
        params:
          paths:
            value: /usr/share/nginx/html
          exclude: 
            value: /usr/share/nginx/html/tmp1